### ISSUE TITLE
README.md correction

### ISSUE THREAD

**Issue by dev-head** [Nordstrom/chef-gen-flavors#12]
It looks like the wrong variable is being documented, in the README.md, for use to skip the flavor options. 

I searched code base for the use of ```CHEFGEN_TEMPLATE``` and did not find one, came across ```CHEFGEN_FLAVOR``` during search; worked like a charm.

#### Incorrect
```
$ CHEFGEN_TEMPLATE=mytemplate chef generate cookbook my_app
```

#### Correct
```
$ CHEFGEN_FLAVOR=mytemplate chef generate cookbook my_app
```

edit: updated to denote file affected

**Comment by jf647** [comment]
Ah, looks like I missed that when renaming from chef-dk-template-plugin to chef-gen-flavors.  Will fix this weekend, thanks.

**Comment by dev-head** [comment]
Docs updated, closing this out. thanks.
