### ISSUE TITLE
Ordering flavors?

### ISSUE THREAD

**Issue by echohack** [Nordstrom/chef-gen-flavors#9]
Is there a way to order flavors? Can we set a "default" flavor?

For example, I've got a bunch of flavors in my gem like so:

└── lib
    └── chef_gen
        └── flavor
            └── base.rb
            └── new.rb
            └── review.rb

The flavor selector currently does reverse alphabetical order inside the gem:

[ChefGen Flavor Selector]: Flavors on the menu
1. pan_review: Review an existing cookbook and validate its correctness.
2. pan_new: Generate a new cookbook with good defaults.
3. pan_base: Generate a base cookbook for organization wide policy.

Not sure how it aggregates other gem flavor's stuff, though. Maybe we can figure a way to order it better?

Is there a way for the user to set a default flavor, perhaps in their knife.rb? (Like, if they just hit enter with no selection it will just pick the default?)

**Comment by jf647** [comment]
There is an environment var to select the flavor to use:

```
M00972939 ➜  ~  chef generate cookbook foo
[ChefGen Flavor Selector]: Flavors on the menu
1. nordstrom: Generic Nordstrom cookbook template
2. nadt: NADT cookbook template
[ChefGen Flavor Selector]: Enter selection: ^C
M00972939 ➜  ~  CHEFGEN_FLAVOR=nadt chef generate cookbook foo
using ChefGen flavor 'nadt' in /Users/x39d/.chefdk/gem/ruby/2.1.0/gems/chef-gen-flavor-nadt-0.2.0/code_generator
..
```

As for the ordering of the menu, LittlePlugger just gives me back a hash of plugin names, which I'm not sorting, so I assume the reverse order you're seeing is due to the way it scans installed gems.  We can certainly add ascending alphabetical order, that seems like a reasonable default.

Does the env var solve the other part of your use case?

**Comment by jf647** [comment]
I just pushed 0.6.2 that sorts the flavors alphabetically.

**Comment by echohack** [comment]
Wow so fast! I will test it out and close the issue if it all works out.

**Comment by echohack** [comment]
Sorry for the delay! I finally got back around to this and it looks good! Closing.
